import sys
import warnings
import uuid


import deepsecurity
from deepsecurity.rest import ApiException

if not sys.warnoptions:
    warnings.simplefilter("ignore")


class TMDS:
    api_version = 'v1'

    def __init__(self, host, api_key):
        self.host = host
        self.api_key = api_key
        self.configuration = deepsecurity.Configuration()
        self.configuration.host = host
        self.configuration.api_key['api-secret-key'] = api_key

    def generate_api_key(self, tenant_id):
        api_instance = deepsecurity.TenantsApi(deepsecurity.ApiClient(self.configuration))
        key_name = 'key_{}'.format(uuid.uuid4())
        api_key = deepsecurity.ApiKey(
            key_name=key_name,
            description='Key generated by TMDS Accounting script',
            role_id=1
        )
        api_response = api_instance.generate_tenant_api_secret_key(
            tenant_id, api_key, self.api_version)
        return api_response.id, api_response.secret_key

    def modify_computer(self, computer_id, computer):
        api_instance = deepsecurity.ComputersApi(deepsecurity.ApiClient(self.configuration))
        overrides = False

#        try:
        api_response = api_instance.modify_computer(computer_id,
                                                    computer,
                                                    self.api_version,
                                                    overrides=overrides)
        return api_response

    def delete_api_key(self, api_key_id):
        api_instance = deepsecurity.APIKeysApi(deepsecurity.ApiClient(self.configuration))
        try:
            api_instance.delete_api_key(api_key_id, self.api_version)
        except ApiException as e:
            print('An exception occurred when calling APIKeysApi.delete_api_key: {e}')

    def tenants(self):
        api_instance = deepsecurity.TenantsApi(deepsecurity.ApiClient(self.configuration))
        api_response = api_instance.list_tenants(self.api_version, async_req=True, _request_timeout=1)
        return api_response.get().tenants

    def computers(self):
        api_instance = deepsecurity.ComputersApi(deepsecurity.ApiClient(self.configuration))
        overrides = False
        try:
            api_response = api_instance.list_computers(self.api_version, overrides=overrides)
        except deepsecurity.rest.ApiException as e:
            if e.status != 401:
                raise
            print('Stored key is wrong')
            sys.exit(1)
        return api_response.computers


AM = 'anti-malware'
WR = 'web-reputation'

FW = 'firewall'
IP = 'intrusion-prevention'

IM = 'integrity-monitoring'
LI = 'log-inspection'
AC = 'application-control'

all_modules = (AM, WR, FW, IP, IM, LI, AC)


AM_S = 'AntiMalware_Security'
N_S = 'Network_Security'
S_S = 'System_Security'
SAP_S = 'SAP_Security'
E_S = 'Enterprise_Security'

all_packages = (AM_S, N_S, S_S, E_S)

packaging = {
    AM: AM_S,
    WR: AM_S,
    FW: N_S,
    IP: N_S,
}

packaging2 = {
    AM_S: (AM, WR),
    N_S: (IP, FW),
    S_S: (AC, LI, IM)
}

def printable(module):
    import re
    l = re.findall(r"[\w]+", module)
    l = [m.capitalize() for m in l]
    return ' '.join(l)



def package(modules):
    packages = set()
    for module in modules:
        packages.add()

def computer_info(computer):
    import pprint
    pprint.pprint(computer)
    agent_active = computer.computer_status.agent_status in ('active', 'error')
    """
    fw = computer.firewall is not None and \
         computer.firewall.module_status.agent_status == 'active'
    ac = computer.application_control is not None and \
         computer.application_control.module_status.agent_status == 'active'
    im = computer.integrity_monitoring is not None and \
         computer.integrity_monitoring.module_status.agent_status == 'active'
    wr = computer.web_reputation is not None and \
         computer.web_reputation.module_status.agent_status == 'active'
    am = computer.anti_malware is not None and \
         computer.anti_malware.module_status.agent_status == 'active'
    ip = computer.intrusion_prevention is not None and \
         computer.intrusion_prevention.module_status.agent_status == 'active'
    #        computer.intrusion_prevention.state != 'off'
    li = computer.log_inspection is not None and \
         computer.log_inspection.module_status.agent_status == 'active'
    """
    fw = computer.firewall is not None and \
         computer.firewall.state != 'off'
    ac = computer.application_control is not None and \
         computer.application_control.state != 'off'
    im = computer.integrity_monitoring is not None and \
         computer.integrity_monitoring.state != 'off'
    wr = computer.web_reputation is not None and \
         computer.web_reputation.state != 'off'
    am = computer.anti_malware is not None and \
         computer.anti_malware.state != 'off'
    ip = computer.intrusion_prevention is not None and \
         computer.intrusion_prevention.state != 'off'
    #        computer.intrusion_prevention.state != 'off'
    li = computer.log_inspection is not None and \
         computer.log_inspection.state != 'off'

    print(fw, ac, im, wr, am, ip, li)
    am_s = am or wr
    n_s = fw or ip
    s_s = ac or im or li
    e_s = int(am_s) + int(n_s) + int(s_s) > 1

    return dict(
        active=int(agent_active),
        modules={
            FW: int(fw),
            AC: int(ac),
            IM: int(im),
            WR: int(wr),
            AM: int(am),
            IP: int(ip),
            LI: int(li)
        },
        packages={
            AM_S: int(am_s),
            N_S: int(n_s),
            S_S: int(s_s),
            E_S: int(e_s)
        }
    )

def computer_modules_state(computer):
    agent_active = computer.computer_status.agent_status in ('active', 'error')
    ### check this later





    fw = computer.firewall is not None and \
         computer.firewall.state != 'off'
    ac = computer.application_control is not None and \
         computer.application_control.state != 'off'
    im = computer.integrity_monitoring is not None and \
         computer.integrity_monitoring.state != 'off'
    wr = computer.web_reputation is not None and \
         computer.web_reputation.state != 'off'
    am = computer.anti_malware is not None and \
         computer.anti_malware.state != 'off'
    ip = computer.intrusion_prevention is not None and \
         computer.intrusion_prevention.state != 'off'
    li = computer.log_inspection is not None and \
         computer.log_inspection.state != 'off'

    return {
        FW: int(fw),
        AC: int(ac),
        IM: int(im),
        WR: int(wr),
        AM: int(am),
        IP: int(ip),
        LI: int(li)
    }
"""        
registered_computers = 'registered_computers'
active_computers = 'active_computers'

FW = 'firewall'
AC = 'application-control'
IM = 'integrity-monitoring'
WR = 'web-reputation'
AM = 'anti-malware'
IP = 'intrusion-prevention'
LI = 'log-inspection'

all_modules = (FW, AC, IM, WR, AM, IP, LI)

AM_S = 'AntiMalware_Security'
N_S = 'Network_Security'
S_S = 'System_Security'
#SAP_S = 'SAP_Security'
E_S = 'Enterprise_Security'

packages = (AM_S, N_S, S_S, E_S)

def add_prefix(prefix, module):
    return f"{prefix}_{module.replace('-', '_')}"

def active(module):
    return add_prefix('active', module)


def provisioned(module):
    return add_prefix('provisioned', module)


def modules_counters(prefix):
    return {add_prefix(prefix, module): 0 for module in all_modules}


def packages_counters():
    return {package: 0 for package in packages}


ALL = 'all'
"""
"""

  Intrusion Prevention		On, Detect, no rules
  
  
/Users/michael/PycharmProjects/azn/venv/bin/python /Users/michael/PycharmProjects/azn/azn.py
2019-05-21 08:44:47.530 Python[7732:1062374] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Total number of tenants: 9
about to create key for 2
got key: 188, 097827F0-A6E3-121A-AAA1-A0F0A8AC01A2:188:h5ez2EPZBI8uZo/EmRnXrch7jbp+N+E+U81afIwUdRM=
{'agent_finger_print': 'FA:E3:7A:7D:B0:CE:AD:3A:4E:FC:13:06:72:EE:57:9C:28:49:B6:F2',
 'agent_version': '11.3.0.292',
 'anti_malware': {'last_manual_scan': None,
                  'last_scheduled_scan': None,
                  'manual_scan_configuration_id': 0,
                  'module_status': {'agent_status': 'inactive',
                                    'agent_status_message': 'Off, installed, '
                                                            'no configuration',
                                    'appliance_status': None,
                                    'appliance_status_message': None},
                  'real_time_scan_configuration_id': 0,
                  'real_time_scan_schedule_id': 0,
                  'scheduled_scan_configuration_id': 0,
                  'state': 'off'},
 'appliance_finger_print': None,
 'application_control': {'block_unrecognized': False,
                         'maintenance_mode_status': 'N/A',
                         'module_status': {'agent_status': 'inactive',
                                           'agent_status_message': 'Off, '
                                                                   'installed',
                                           'appliance_status': None,
                                           'appliance_status_message': None},
                         'ruleset_id': None,
                         'state': 'off'},
 'asset_importance_id': None,
 'azure_arm_virtual_machine_summary': None,
 'azure_vm_virtual_machine_summary': None,
 'bios_uuid': '4234bb63-d359-53d5-f441-13405459c018',
 'computer_settings': {'anti_malware_setting_behavior_monitoring_scan_exclusion_list': {'value': ''},
                       'anti_malware_setting_combined_mode_protection_source': {'value': 'Appliance '
                                                                                         'preferred'},
                       'anti_malware_setting_connected_threat_defense_suspicious_file_ddan_submission_enabled': {'value': 'true'},
                       'anti_malware_setting_connected_threat_defense_use_control_manager_suspicious_object_list_enabled': {'value': 'true'},
                       'anti_malware_setting_document_exploit_protection_rule_exceptions': {'value': ''},
                       'anti_malware_setting_file_hash_enabled': {'value': 'false'},
                       'anti_malware_setting_file_hash_md5_enabled': {'value': 'false'},
                       'anti_malware_setting_file_hash_sha256_enabled': {'value': 'false'},
                       'anti_malware_setting_file_hash_size_max_mbytes': {'value': '128'},
                       'anti_malware_setting_identified_files_space_max_mbytes': {'value': '1024'},
                       'anti_malware_setting_malware_scan_multithreaded_processing_enabled': {'value': 'false'},
                       'anti_malware_setting_nsx_security_tagging_enabled': {'value': 'true'},
                       'anti_malware_setting_nsx_security_tagging_on_remediation_failure_enabled': {'value': 'true'},
                       'anti_malware_setting_nsx_security_tagging_remove_on_clean_scan_enabled': {'value': 'true'},
                       'anti_malware_setting_nsx_security_tagging_value': {'value': 'ANTI_VIRUS.VirusFound.threat=medium'},
                       'anti_malware_setting_predictive_machine_learning_exceptions': {'value': ''},
                       'anti_malware_setting_scan_cache_on_demand_config_id': {'value': ''},
                       'anti_malware_setting_scan_cache_real_time_config_id': {'value': ''},
                       'anti_malware_setting_scan_file_size_max_mbytes': {'value': '0'},
                       'anti_malware_setting_smart_protection_global_server_enabled': {'value': 'true'},
                       'anti_malware_setting_smart_protection_global_server_use_proxy_enabled': {'value': 'false'},
                       'anti_malware_setting_smart_protection_local_server_allow_off_domain_global': {'value': 'false'},
                       'anti_malware_setting_smart_protection_local_server_urls': {'value': ''},
                       'anti_malware_setting_smart_protection_server_connection_lost_warning_enabled': {'value': 'true'},
                       'anti_malware_setting_smart_scan_state': {'value': 'Automatic'},
                       'anti_malware_setting_spyware_approved_list': {'value': ''},
                       'anti_malware_setting_syslog_config_id': {'value': '0'},
                       'anti_malware_setting_virtual_appliance_on_demand_scan_cache_entries_max': {'value': '500000'},
                       'anti_malware_setting_virtual_appliance_real_time_scan_cache_entries_max': {'value': '500000'},
                       'application_control_setting_execution_enforcement_level': {'value': 'Allow '
                                                                                            'unrecognized '
                                                                                            'software '
                                                                                            'until '
                                                                                            'it '
                                                                                            'is '
                                                                                            'explicitly '
                                                                                            'blocked'},
                       'application_control_setting_ruleset_mode': {'value': 'Use '
                                                                             'local '
                                                                             'ruleset'},
                       'application_control_setting_shared_ruleset_id': {'value': '0'},
                       'application_control_setting_syslog_config_id': {'value': '0'},
                       'firewall_setting_anti_evasion_check_evasive_retransmit': {'value': 'Allow'},
                       'firewall_setting_anti_evasion_check_fin_no_connection': {'value': 'Allow'},
                       'firewall_setting_anti_evasion_check_fragmented_packets': {'value': 'Allow'},
                       'firewall_setting_anti_evasion_check_out_no_connection': {'value': 'Allow'},
                       'firewall_setting_anti_evasion_check_paws': {'value': 'Ignore'},
                       'firewall_setting_anti_evasion_check_rst_no_connection': {'value': 'Allow'},
                       'firewall_setting_anti_evasion_check_tcp_checksum': {'value': 'Allow'},
                       'firewall_setting_anti_evasion_check_tcp_congestion_flags': {'value': 'Allow'},
                       'firewall_setting_anti_evasion_check_tcp_paws_zero': {'value': 'Allow'},
                       'firewall_setting_anti_evasion_check_tcp_rst_fin_flags': {'value': 'Deny'},
                       'firewall_setting_anti_evasion_check_tcp_split_handshake': {'value': 'Deny'},
                       'firewall_setting_anti_evasion_check_tcp_syn_fin_flags': {'value': 'Deny'},
                       'firewall_setting_anti_evasion_check_tcp_syn_rst_flags': {'value': 'Deny'},
                       'firewall_setting_anti_evasion_check_tcp_syn_with_data': {'value': 'Deny'},
                       'firewall_setting_anti_evasion_check_tcp_urgent_flags': {'value': 'Allow'},
                       'firewall_setting_anti_evasion_check_tcp_zero_flags': {'value': 'Deny'},
                       'firewall_setting_anti_evasion_security_posture': {'value': 'Normal'},
                       'firewall_setting_anti_evasion_tcp_paws_window_policy': {'value': '0'},
                       'firewall_setting_combined_mode_protection_source': {'value': 'Agent '
                                                                                     'preferred'},
                       'firewall_setting_config_package_exceeds_alert_max_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_ack_timeout': {'value': '1 '
                                                                               'Second'},
                       'firewall_setting_engine_option_allow_null_ip_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_block_ipv6_agent8_and_earlier_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_block_ipv6_agent9_and_later_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_block_same_src_dst_ip_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_boot_start_timeout': {'value': '20 '
                                                                                      'Seconds'},
                       'firewall_setting_engine_option_bypass_cisco_waas_connections_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_close_timeout': {'value': '0 '
                                                                                 'Seconds'},
                       'firewall_setting_engine_option_close_wait_timeout': {'value': '2 '
                                                                                      'Minutes'},
                       'firewall_setting_engine_option_closing_timeout': {'value': '1 '
                                                                                   'Second'},
                       'firewall_setting_engine_option_cold_start_timeout': {'value': '5 '
                                                                                      'Minutes'},
                       'firewall_setting_engine_option_connection_cleanup_timeout': {'value': '10 '
                                                                                              'Seconds'},
                       'firewall_setting_engine_option_connections_cleanup_max': {'value': '1000'},
                       'firewall_setting_engine_option_connections_num_icmp_max': {'value': '10000'},
                       'firewall_setting_engine_option_connections_num_tcp_max': {'value': '1000000'},
                       'firewall_setting_engine_option_connections_num_udp_max': {'value': '1000000'},
                       'firewall_setting_engine_option_debug_mode_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_debug_packet_num_max': {'value': '8'},
                       'firewall_setting_engine_option_disconnect_timeout': {'value': '60 '
                                                                                      'Seconds'},
                       'firewall_setting_engine_option_drop6_to4_bogons_addresses_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_drop_evasive_retransmit_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_drop_ip_zero_payload_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_drop_ipv6_bogons_addresses_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_drop_ipv6_ext_type0_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_drop_ipv6_fragments_lower_than_min_mtu_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_drop_ipv6_reserved_addresses_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_drop_ipv6_site_local_addresses_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_drop_teredo_anomalies_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_drop_unknown_ssl_protocol_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_error_timeout': {'value': '10 '
                                                                                 'Seconds'},
                       'firewall_setting_engine_option_established_timeout': {'value': '3 '
                                                                                       'Hours'},
                       'firewall_setting_engine_option_event_nodes_max': {'value': '20000'},
                       'firewall_setting_engine_option_filter_ipv4_tunnels': {'value': 'Disable '
                                                                                       'Detection '
                                                                                       'of '
                                                                                       'IPv4 '
                                                                                       'Tunnels'},
                       'firewall_setting_engine_option_filter_ipv6_tunnels': {'value': 'Disable '
                                                                                       'Detection '
                                                                                       'of '
                                                                                       'IPv6 '
                                                                                       'Tunnels'},
                       'firewall_setting_engine_option_fin_wait1_timeout': {'value': '2 '
                                                                                     'Minutes'},
                       'firewall_setting_engine_option_force_allow_dhcp_dns': {'value': 'Allow '
                                                                                        'DNS '
                                                                                        'Query '
                                                                                        'and '
                                                                                        'DHCP '
                                                                                        'Client'},
                       'firewall_setting_engine_option_force_allow_icmp_type3_code4': {'value': 'Add '
                                                                                                'Force '
                                                                                                'Allow '
                                                                                                'rule '
                                                                                                'for '
                                                                                                'ICMP '
                                                                                                'type3 '
                                                                                                'code4'},
                       'firewall_setting_engine_option_fragment_offset_min': {'value': '60'},
                       'firewall_setting_engine_option_fragment_size_min': {'value': '120'},
                       'firewall_setting_engine_option_generate_connection_events_icmp_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_generate_connection_events_tcp_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_generate_connection_events_udp_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_icmp_timeout': {'value': '60 '
                                                                                'Seconds'},
                       'firewall_setting_engine_option_ignore_status_code0': {'value': 'None'},
                       'firewall_setting_engine_option_ignore_status_code1': {'value': 'None'},
                       'firewall_setting_engine_option_ignore_status_code2': {'value': 'None'},
                       'firewall_setting_engine_option_last_ack_timeout': {'value': '30 '
                                                                                    'Seconds'},
                       'firewall_setting_engine_option_log_all_packet_data_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_log_events_per_second_max': {'value': '100'},
                       'firewall_setting_engine_option_log_one_packet_period': {'value': '5 '
                                                                                         'Minutes'},
                       'firewall_setting_engine_option_log_one_packet_within_period_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_log_packet_length_max': {'value': '1500 '
                                                                                         'Bytes'},
                       'firewall_setting_engine_option_logging_policy': {'value': 'Default'},
                       'firewall_setting_engine_option_silent_tcp_connection_drop_enabled': {'value': 'false'},
                       'firewall_setting_engine_option_ssl_session_size': {'value': 'Low '
                                                                                    '- '
                                                                                    '2500'},
                       'firewall_setting_engine_option_ssl_session_time': {'value': '24 '
                                                                                    'Hours'},
                       'firewall_setting_engine_option_strict_terodo_port_check_enabled': {'value': 'true'},
                       'firewall_setting_engine_option_syn_rcvd_timeout': {'value': '60 '
                                                                                    'Seconds'},
                       'firewall_setting_engine_option_syn_sent_timeout': {'value': '20 '
                                                                                    'Seconds'},
                       'firewall_setting_engine_option_tcp_mss_limit': {'value': 'No '
                                                                                 'Limit'},
                       'firewall_setting_engine_option_tunnel_depth_max': {'value': '1'},
                       'firewall_setting_engine_option_tunnel_depth_max_exceeded_action': {'value': 'Drop'},
                       'firewall_setting_engine_option_udp_timeout': {'value': '10 '
                                                                               'Seconds'},
                       'firewall_setting_engine_option_verify_tcp_checksum_enabled': {'value': 'false'},
                       'firewall_setting_engine_options_enabled': {'value': 'false'},
                       'firewall_setting_event_log_file_cached_entries_life_time': {'value': '30 '
                                                                                             'Minutes'},
                       'firewall_setting_event_log_file_cached_entries_num': {'value': '128'},
                       'firewall_setting_event_log_file_cached_entries_stale_time': {'value': '15 '
                                                                                              'Minutes'},
                       'firewall_setting_event_log_file_ignore_source_ip_list_id': {'value': ''},
                       'firewall_setting_event_log_file_retain_num': {'value': '3'},
                       'firewall_setting_event_log_file_size_max': {'value': '4 '
                                                                             'MB'},
                       'firewall_setting_events_out_of_allowed_policy_enabled': {'value': 'true'},
                       'firewall_setting_failure_response_engine_system': {'value': 'Fail '
                                                                                    'closed'},
                       'firewall_setting_failure_response_packet_sanity_check': {'value': 'Fail '
                                                                                          'closed'},
                       'firewall_setting_interface_isolation_enabled': {'value': 'false'},
                       'firewall_setting_interface_limit_one_active_enabled': {'value': 'false'},
                       'firewall_setting_interface_patterns': {'value': ''},
                       'firewall_setting_network_engine_mode': {'value': 'Inline'},
                       'firewall_setting_reconnaissance_block_fingerprint_probe_duration': {'value': 'No'},
                       'firewall_setting_reconnaissance_block_network_or_port_scan_duration': {'value': 'No'},
                       'firewall_setting_reconnaissance_block_tcp_null_scan_duration': {'value': 'No'},
                       'firewall_setting_reconnaissance_block_tcp_syn_fin_scan_duration': {'value': 'No'},
                       'firewall_setting_reconnaissance_block_tcp_xmas_attack_duration': {'value': 'No'},
                       'firewall_setting_reconnaissance_detect_fingerprint_probe_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_detect_network_or_port_scan_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_detect_tcp_null_scan_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_detect_tcp_syn_fin_scan_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_detect_tcp_xmas_attack_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_exclude_ip_list_id': {'value': ''},
                       'firewall_setting_reconnaissance_include_ip_list_id': {'value': ''},
                       'firewall_setting_reconnaissance_notify_fingerprint_probe_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_notify_network_or_port_scan_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_notify_tcp_null_scan_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_notify_tcp_syn_fin_scan_enabled': {'value': 'true'},
                       'firewall_setting_reconnaissance_notify_tcp_xmas_attack_enabled': {'value': 'true'},
                       'firewall_setting_virtual_and_container_network_scan_enabled': {'value': 'false'},
                       'integrity_monitoring_setting_auto_apply_recommendations_enabled': {'value': 'No'},
                       'integrity_monitoring_setting_combined_mode_protection_source': {'value': 'Appliance '
                                                                                                 'preferred'},
                       'integrity_monitoring_setting_content_hash_algorithm': {'value': 'sha1'},
                       'integrity_monitoring_setting_cpu_usage_level': {'value': 'High'},
                       'integrity_monitoring_setting_realtime_enabled': {'value': 'false'},
                       'integrity_monitoring_setting_scan_cache_config_id': {'value': ''},
                       'integrity_monitoring_setting_syslog_config_id': {'value': '0'},
                       'integrity_monitoring_setting_virtual_appliance_optimization_scan_cache_entries_max': {'value': '500000'},
                       'intrusion_prevention_setting_auto_apply_recommendations_enabled': {'value': 'No'},
                       'intrusion_prevention_setting_combined_mode_protection_source': {'value': 'Agent '
                                                                                                 'preferred'},
                       'intrusion_prevention_setting_engine_option_fragmented_ip_keep_max': {'value': '1000'},
                       'intrusion_prevention_setting_engine_option_fragmented_ip_packet_send_icmp_enabled': {'value': 'true'},
                       'intrusion_prevention_setting_engine_option_fragmented_ip_timeout': {'value': '60 '
                                                                                                     'Seconds'},
                       'intrusion_prevention_setting_engine_option_fragmented_ip_unconcerned_mac_address_bypass_enabled': {'value': 'false'},
                       'intrusion_prevention_setting_engine_options_enabled': {'value': 'false'},
                       'intrusion_prevention_setting_log_data_rule_first_match_enabled': {'value': 'true'},
                       'intrusion_prevention_setting_nsx_security_tagging_detect_mode_level': {'value': 'No '
                                                                                                        'Tagging'},
                       'intrusion_prevention_setting_nsx_security_tagging_prevent_mode_level': {'value': 'No '
                                                                                                         'Tagging'},
                       'intrusion_prevention_setting_virtual_and_container_network_scan_enabled': {'value': 'true'},
                       'log_inspection_setting_auto_apply_recommendations_enabled': {'value': 'No'},
                       'log_inspection_setting_severity_clipping_agent_event_send_syslog_level_min': {'value': 'Medium '
                                                                                                               '(6)'},
                       'log_inspection_setting_severity_clipping_agent_event_store_level_min': {'value': 'Medium '
                                                                                                         '(6)'},
                       'log_inspection_setting_syslog_config_id': {'value': '0'},
                       'platform_setting_agent_communications_direction': {'value': 'Bidirectional'},
                       'platform_setting_agent_events_send_interval': {'value': '60 '
                                                                                'Seconds'},
                       'platform_setting_agent_self_protection_enabled': {'value': 'false'},
                       'platform_setting_agent_self_protection_password': {'value': ''},
                       'platform_setting_agent_self_protection_password_enabled': {'value': 'false'},
                       'platform_setting_auto_assign_new_intrusion_prevention_rules_enabled': {'value': 'true'},
                       'platform_setting_auto_update_anti_malware_engine_enabled': {'value': 'false'},
                       'platform_setting_combined_mode_network_group_protection_source': {'value': 'Agent '
                                                                                                   'preferred'},
                       'platform_setting_environment_variable_overrides': {'value': ''},
                       'platform_setting_heartbeat_inactive_vm_offline_alert_enabled': {'value': 'false'},
                       'platform_setting_heartbeat_interval': {'value': '10 '
                                                                        'Minutes'},
                       'platform_setting_heartbeat_local_time_shift_alert_threshold': {'value': 'Unlimited'},
                       'platform_setting_heartbeat_missed_alert_threshold': {'value': '2'},
                       'platform_setting_inactive_agent_cleanup_override_enabled': {'value': 'false'},
                       'platform_setting_notifications_suppress_popups_enabled': {'value': 'false'},
                       'platform_setting_recommendation_ongoing_scans_interval': {'value': '7 '
                                                                                           'Days'},
                       'platform_setting_relay_state': {'value': 'false'},
                       'platform_setting_scan_cache_concurrency_max': {'value': '1'},
                       'platform_setting_scan_open_port_list_id': {'value': '1-1024'},
                       'platform_setting_smart_protection_anti_malware_global_server_proxy_id': {'value': ''},
                       'platform_setting_smart_protection_global_server_enabled': {'value': 'true'},
                       'platform_setting_smart_protection_global_server_proxy_id': {'value': ''},
                       'platform_setting_smart_protection_global_server_use_proxy_enabled': {'value': 'false'},
                       'platform_setting_troubleshooting_logging_level': {'value': 'Do '
                                                                                   'Not '
                                                                                   'Override'},
                       'platform_setting_upgrade_on_activation_enabled': {'value': 'false'},
                       'web_reputation_setting_alerting_enabled': {'value': 'false'},
                       'web_reputation_setting_allowed_url_domains': {'value': ''},
                       'web_reputation_setting_allowed_urls': {'value': ''},
                       'web_reputation_setting_blocked_url_domains': {'value': ''},
                       'web_reputation_setting_blocked_url_keywords': {'value': ''},
                       'web_reputation_setting_blocked_urls': {'value': ''},
                       'web_reputation_setting_blocking_page_link': {'value': 'http://sitesafety.trendmicro.com/'},
                       'web_reputation_setting_combined_mode_protection_source': {'value': 'Agent '
                                                                                           'preferred'},
                       'web_reputation_setting_monitor_port_list_id': {'value': '80,8080'},
                       'web_reputation_setting_security_block_untested_pages_enabled': {'value': 'false'},
                       'web_reputation_setting_security_level': {'value': 'Medium'},
                       'web_reputation_setting_smart_protection_global_server_use_proxy_enabled': {'value': 'false'},
                       'web_reputation_setting_smart_protection_local_server_allow_off_domain_global': {'value': 'false'},
                       'web_reputation_setting_smart_protection_local_server_enabled': {'value': 'false'},
                       'web_reputation_setting_smart_protection_local_server_urls': {'value': ''},
                       'web_reputation_setting_smart_protection_server_connection_lost_warning_enabled': {'value': 'true'},
                       'web_reputation_setting_smart_protection_web_reputation_global_server_proxy_id': {'value': ''},
                       'web_reputation_setting_syslog_config_id': {'value': '0'}},
 'computer_status': {'agent_status': 'active',
                     'agent_status_messages': ['Managed (Online)'],
                     'appliance_status': None,
                     'appliance_status_messages': None},
 'description': '',
 'display_name': '',
 'ec2_virtual_machine_summary': None,
 'esx_summary': None,
 'esxsummary': None,
 'firewall': {'global_stateful_configuration_id': None,
              'module_status': {'agent_status': 'inactive',
                                'agent_status_message': 'On, no rules',
                                'appliance_status': None,
                                'appliance_status_message': None},
              'rule_ids': None,
              'state': 'on',
              'stateful_configuration_assignments': None},
 'group_id': 0,
 'host_name': '10.15.184.121',
 'id': 1,
 'integrity_monitoring': {'last_baseline_created': 1556353244959,
                          'last_integrity_scan': None,
                          'module_status': {'agent_status': 'inactive',
                                            'agent_status_message': 'On, no '
                                                                    'rules',
                                            'appliance_status': None,
                                            'appliance_status_message': None},
                          'rule_ids': None,
                          'state': 'on'},
 'interfaces': {'interfaces': [{'detected': True,
                                'dhcp': True,
                                'display_name': '',
                                'id': 1,
                                'interface_type_id': None,
                                'ips': None,
                                'mac': '00:50:56:B4:05:5B',
                                'name': 'Ethernet'}]},
 'intrusion_prevention': {'module_status': {'agent_status': 'inactive',
                                            'agent_status_message': 'On, '
                                                                    'Detect, '
                                                                    'no rules',
                                            'appliance_status': None,
                                            'appliance_status_message': None},
                          'rule_ids': None,
                          'state': 'detect'},
 'last_agent_communication': 1558417023356,
 'last_appliance_communication': None,
 'last_ip_used': '10.15.184.121',
 'last_send_policy_request': 1558092414429,
 'last_send_policy_success': 1558092421960,
 'log_inspection': {'module_status': {'agent_status': 'inactive',
                                      'agent_status_message': 'On, no rules',
                                      'appliance_status': None,
                                      'appliance_status_message': None},
                    'rule_ids': None,
                    'state': 'on'},
 'no_connector_virtual_machine_summary': None,
 'platform': 'Microsoft Windows Server 2012 R2 (64 bit)  Build 9600',
 'policy_id': None,
 'relay_list_id': 0,
 'sap': None,
 'security_updates': None,
 'tasks': None,
 'vmware_vm_virtual_machine_summary': None,
 'web_reputation': {'module_status': {'agent_status': 'inactive',
                                      'agent_status_message': 'Off, installed',
                                      'appliance_status': None,
                                      'appliance_status_message': None},
                    'state': 'off'},
 'workspace_virtual_machine_summary': None}
False False False False False False False
Done id=2)

"""
